spring:
  application:
    name: core-service

server:
  port: 8100

logging:
  level:
    ROOT: INFO
    com.iot: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

