server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JacekGos/iot-data-processor-config-server-repository.git
          default-label: main
          username: JacekGos
          password: ${GITHUB_TOKEN}
          clone-on-start: true
#        bootstrap: false
    fail-fast: true

log:
  app-name: config-service